/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'mobileNumber' : IDL.Text,
  'revenueRange' : IDL.Text,
  'email' : IDL.Text,
  'operationalBottleneck' : IDL.Text,
  'message' : IDL.Text,
  'companyName' : IDL.Text,
  'lastName' : IDL.Text,
  'industry' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'mobileNumber' : IDL.Text,
    'revenueRange' : IDL.Text,
    'email' : IDL.Text,
    'operationalBottleneck' : IDL.Text,
    'message' : IDL.Text,
    'companyName' : IDL.Text,
    'lastName' : IDL.Text,
    'industry' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    'addLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };